string class #955
fork-commit-merge/fork-commit-merge pull request #1538
Opened 2023-11-13 20:36 UTC by alfabeat

## Pull Request Type

What kind of change does this PR introduce?

[ ] Solved an issue/task

## What is the current behavior?
string class

Issue Number: [#955 ]

## What is the new behavior?

added string class
## Other information

2023-11-14 06:52 UTC, nikohoffren requested changes

2023-11-14 06:52 UTC, nikohoffren commented on tasks/c++/hard/mystring.cpp
>  }
The class looks mostly good but it does not quite work. It prints only `Hello` when executing, and i think the problem might be not using proper memory allocation for temp.str in the operator+ method, which will cause it to crash. If you can fix that, i can merge this PR.

2023-11-15 19:51 UTC, nikohoffren commented
Just as a reminder, bot will close this PR if yoi don't respond to the review in two days from now.

2023-11-15 23:31 UTC, alfabeat commented
thank you for the reminder

2023-11-16 06:24 UTC, nikohoffren approved these changes
Thanks! The program seems to be working as expected now.

2023-11-16 06:25 UTC, merged

2023-11-16 06:25 UTC, nikohoffren commented
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!